language: erlang

otp_release:
   - 21.3

before_install:
   - git clone https://github.com/erlang/rebar3.git; cd rebar3; ./bootstrap; sudo mv rebar3 /usr/local/bin/; cd ..

script:
  - make xref
  - make eunit
  - make ct

after_success:
  - make coveralls

sudo: false
